services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP connection port
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dizertatie_shared_net

volumes:
  rabbitmq_data:

networks:
  dizertatie_shared_net:
    name: dizertatie_shared_net
